Repository NOON-official/scheduling_server, pull requests merged in 2022-05, with the labels that each got.

#10 [FIX] typo raw to rows
  src/db/card.js
Labels: fix

#12 Feat/11 log
  .gitignore
  package.json
  src/api/card/cardGET.js
  src/api/card/cardPOST.js
  src/app.js
  src/config/winston.js
  yarn.lock
Labels: enhancement

#20 Feat/19 card update
  src/api/card/cardPUT.js
  src/api/card/index.js
  src/constants/responseMessage.js
  src/db/card.js
  src/lib/swagger.json
Labels: API
